#!/bin/bash
main() {
  git remote update --prune || exit

  git gc --aggressive --prune=now || exit

  git br -r \
  | while read b; do
    h=$(git rev-parse "${b}")
    echo "${h} ${b}"
  done \
  | sort

  echo "To push:"
  echo "git push zenczykowski/proxy-anywhere-extension HEAD:maze"
}

main "$@"; exit
